### ISSUE TITLE
Action escapes underscores and likely other characters unexpectedly.

### ISSUE THREAD

**Issue by andyfeller** [zentered/issue-forms-body-parser#16]
### Describe the bug

Action is escaping underscores from issue form parsing.

### To reproduce

1. Create issue form with input and/or textarea field types
2. Create workflow triggered on new issue creation that parses issue form and passes output to step

   ```yaml
       steps:
         - name: Cloning repository for reusable scripts
           uses: actions/checkout@v2
    
         - name: Parse issue form
           id: parse
           uses: zentered/issue-forms-body-parser@v1.4.4
    
         - name: Record issue form results
           uses: actions/github-script@v6
           env:
             ISSUE_FORM_JSON: ${{ steps.parse.outputs.data }}
           with:
             script: |
               const issueForm = JSON.parse(process.env.ISSUE_FORM_JSON)
               const jsonPretty = JSON.stringify(issueForm, null, 2)
               const body = `
               Nice!  Let's validate the issue form so we can get this thing done!
               <details>
                 <summary>Issue Form Payload</summary>
                 \`\`\`json
                 ${jsonPretty}
                 \`\`\`
               </details>
               `
               github.rest.issues.createComment({
                 ...context.repo,
                 issue_number: context.issue.number,
                 body
               })
   ```
3. Create issue and verify processed JSON output with escaped underscores

   ```json
   {"repository-name":{"title":"Repository name","content":["check\\_underscores\\_2"],"text":"check\\_underscores\\_2"},"repository-description":{"title":"Repository description","content":["*No response*"],"text":"*No response*"},"repository-visibility":{"title":"Repository visibility","content":["Internal"],"text":"Internal"},"repository-justification":{"title":"Repository justification","content":["*No response*"],"text":"*No response*"},"repository-access":{"title":"Repository access","content":["@tinyfists/under\\_scores , read"],"text":"@tinyfists/under\\_scores , read"}}
   ```

### Expected behaviour

There might be a good reason for this, so either:

1. Review whether this is intended and provide docs for users to de-escape text as needed
2. Modify action to de-escape text resulting from parsing

**Comment by PatrickHeneise** [comment]
Thanks for the report, @andyfeller! That's definitely not intentional.

I'm missing the input data to reproduce this; can you add the case and expected results to the test cases, then we'll be able to fix that.

**Comment by andyfeller** [comment]
@PatrickHeneise : as always, I wish I could give you ✨ as a hubber!

Here's the issue body from my most recent test:

> ### Repository name
> 
> check_underscores_2
> 
> ### Repository description
> 
> _No response_
> 
> ### Repository visibility
> 
> Internal
> 
> ### Repository justification
> 
> _No response_
> 
> ### Repository access
> 
> @tinyfists/under_scores , read

**Comment by PatrickHeneise** [comment]
Thanks. Let me see what I can do

**Comment by PatrickHeneise** [comment]
Alright, this is a little tricky ...

here's the test result (I just added the lines to `test/test-issue-1.md` and run with `npm test`):

```
    "repository-name": Object {                   
      "title": "Repository name",                 
      "content": Array [                          
        "check\\_underscores\\_2",                
      ],                                          
      "text": "check\\_underscores\\_2",          
    },                                            
    "repository-description": Object {            
      "title": "Repository description",          
      "content": Array [                          
        "*No response*",                          
      ],                                          
      "text": "*No response*",                    
    },                                            
    "repository-visibility": Object {             
      "title": "Repository visibility",           
      "content": Array [                          
        "Internal",                               
      ],                                          
      "text": "Internal",                         
    },                                            
    "repository-justification": Object {          
      "title": "Repository justification",        
      "content": Array [                          
        "*No response*",                          
      ],                                          
      "text": "*No response*",                    
    },                                            
    "repository-access": Object {                 
      "title": "Repository access",               
      "content": Array [                          
        "@tinyfists/under\\_scores , read",       
      ],                                          
      "text": "@tinyfists/under\\_scores , read", 
    },                                            
   }  
```

`\\_` seems to come from the Markdown parser. 

In the future, if this happens again for other characters, the easiest workaround would be if you can use `code tags`:

```
    "repository-access": Object {          
      "title": "Repository access",        
      "content": Array [                   
        "`@tinyfists/under_scores`",       
      ],                                   
      "text": "`@tinyfists/under_scores`", 
    }
```

For the underscores, I [added a fix here](https://github.com/zentered/issue-forms-body-parser/pull/17). I don't see any breaking changes, but it would be great if you could test it before.

Also, if you have more cases, please add them to `test-issue-1.md` or create a separate issue where we can make sure we cover all the possibilities and I don't break stuff with a new release :)

**Comment by andyfeller** [comment]
As always, thank you, Patrick!  I can work with @apdarr next week to bump the version and test it out!  I recognize this is a downstream issue, so appreciate your efforts to building a better product.

Anything a user can do to tell the parser to ignore or undo the escaping without having to bother you is always a plus.

**Comment by PatrickHeneise** [comment]
Let's hope that's the only issue in the markdown parser :) and let me know if there's anything else. As mentioned, if you have  more cases that could be useful for testing, just add them to the test file and I'll add the test cases to it. Eventually I also want to support markdown frontmatter and a few other edge cases (ie paragraph with no heading) - when there's time.

I'll merge and bump the version after you give the green light

**Comment by andyfeller** [comment]
Carving out some weekend time to test it now ...

**Comment by PatrickHeneise** [comment]
Thank you!

**Comment by andyfeller** [comment]
No; thank you, Patrick! 🙇 I'm happy to be your biggest advocate!
