### ISSUE TITLE
Old setOutput function before @actions/core 1.10.0 is deprecated

### ISSUE THREAD

**Issue by Kas-tle** [zentered/issue-forms-body-parser#20]
### Describe the bug

The old setOutput function is deprecated and its use leads to the following deprecation warning:
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

### To reproduce

Use the action and observe that calling it produces a deprecation warning.
See https://github.com/Kas-tle/java2bedrock.sh/actions/runs/3247277630 for example.

### Expected behaviour

No deprecation warning occurs.

### Additional context

This can be remedied by upgrading the [`@actions/core` package to 1.10.0](https://github.com/zentered/issue-forms-body-parser/blob/main/package.json#L65) as described here:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by PatrickHeneise** [comment]
Thanks, will take care of that with the next update.

**Comment by Kas-tle** [comment]
Thanks so much!
