### ISSUE TITLE
Body containing hours triggers date-fns parsing and error

### ISSUE THREAD

**Issue by framp** [zentered/issue-forms-body-parser#30]
### Describe the bug

When an issue contains hours at the beginning of a line we try to parse it as an hour and date-fns crashes.

This is what we're sending to date-fns parse:
```
1) 19:00 - 19:45 - "Workflow automation with GitHub Actions"
Yuri Trykov (inDrive)
Automation is a crucial aspect of fast code delivery, and GitHub Actions is a simple and convenient tool to automate the development workflow right in your GitHub repository. In this talk, I am going to cover basic scenarios: testing, building and deploying code, and integration with external services. Moreover, I will share some tips for creating effective automation and fixing common problems.
2) hh:mm A 
3) 2023-09-05T18:51:53.608Z 
4) undefined

```
This eventually fails because of the A with
```
Issue 'CDC Test failed': RangeError: Format string contains an unescaped latin alphabet character `A`
```

### To reproduce

This is the original string which reproduces the error:

`### Event Description\n\nWe are happy to announce the first meetup of CocoaHeads Cyprus! Let's gather and have some fun. Talks would be in English. [Reserve a spot here](https://www. eventbrite. com/e/cocoaheads-cyprus-0604-tickets-596834436867).\n\nAgenda\n\n18:30- 19:00 - Gathering & Intro\n\n19:00 - 19:45 - "Workflow automation with GitHub Actions"\nYuri Trykov (inDrive)\nAutomation is a crucial aspect of fast code delivery, and GitHub Actions is a simple and convenient tool to automate the development workflow right in your GitHub repository. In this talk, I am going to cover basic scenarios: testing, building and deploying code, and integration with external services. Moreover, I will share some tips for creating effective automation and fixing common problems.\n\n19:45 - 20:00 - Coffee Break & Networking\n\n20:00 - 20:45 - "Boosting your pet-project with ChatGPT"\nAlexey Levanov (Exness)\nVery often pet projects are not completed due to lack of time, loss of motivation, or workload. If your pet project is a completed mobile application, in addition to development, you need design and promotion. It is quite difficult to engage in development, UI/UX prototyping, and marketing at the same time. Let's see how currently available neural networks can help you to accelerate the development of your pet project and replace competencies that you don't possess.\n\n20:45 - 21:00 - Networking\n\n### Location\n\nPorto Bello, Limassol\n\n### Date\n\n06.04.2023\n\n### Time\n\n18.30\n\n### Duration\n\n2h30m\n\n### Code of Conduct\n\n- [X] I agree to follow this project's [Code of Conduct](https://berlincodeofconduct. org)`

### Expected behaviour

The body parses correctly without errors

### Additional context

We could definitely improve the parsing logic (or handle exceptions) but I was wondering if you thought about dealing with parsing based on the header.

In that way whatever content is in the Event Description won't matter and we'll accept only dates in `Date` or times in `Time`.

**Comment by PatrickHeneise** [comment]
Thanks for reporting this!

There's another GitHub action that does header-matching which is a great alternative. I think it'd be great to stay flexible and try to automatically determine the type of the field, with improved parser logic. What would be your suggestion?

**Comment by framp** [comment]
Oh my bad! I see you already fixed it in the latest version:
https://github.com/zentered/issue-forms-body-parser/commit/b41f51e6926f3a6a07b8f56625cef17f5214a5e7

Removing that 'hh:mm A' should make this particular error impossible to trigger

I'll keep an eye if anything else pops up

Thanks and sorry for the noise ^^
